{{- if .Values.components.console.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "owl.fullname" . }}-console
  labels:
    {{- include "owl.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "owl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: console
{{- end }}