{{/*}}
不指定configmap时,创建默认conigmap
{{*/}}
{{- if empty .Values.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home.configMap" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "home.labels" . | nindent 4 }}
data:
  db.user: {{ .Values.config.database.user | quote }}
  db.host: {{ .Values.config.database.host | quote }}
  db.ssl: {{ .Values.config.database.ssl | quote }}
  db.database: {{ .Values.config.database.database | quote }}
  db.port: {{ .Values.config.database.port | quote }}

  web.listen: {{ .Values.config.web.listen | quote }}
  web.cache: {{ .Values.config.web.cache | quote }}
{{- end }}
