{{/*}}
不指定secret时,创建默认secret
{{*/}}
{{- if empty .Values.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "home.labels" . | nindent 4 }}
type: Opaque
data:
  db.password: {{ .Values.config.database.password | b64enc | quote }}
{{- end }}