apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zoo.fullname" . }}
  labels:
    {{- include "zoo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount}}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zoo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zoo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WEB_Listen
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: web.listen
          - name: WEB_CACHE
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: web.cache
          - name: WEB_WEBSITEID
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: web.webSiteId

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "zoo.secret" . }}
                key: db.password
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: db.user
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: db.host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: db.port
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: db.database
          - name: DB_SSL
            valueFrom:
              configMapKeyRef:
                name: {{ include "zoo.configMap" . }}
                key: db.ssl
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}