{{/*}}
不指定configmap时,创建默认conigmap
{{*/}}
{{- if empty .Values.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "owl.configMap" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "owl.labels" . | nindent 4 }}
data:
  db.user: {{ .Values.config.database.user | quote }}
  db.host: {{ .Values.config.database.host | quote }}
  db.ssl: {{ .Values.config.database.ssl | quote }}
  db.database: {{ .Values.config.database.database | quote }}
  db.port: {{ .Values.config.database.port | quote }}

  token.enable: {{ .Values.config.token.enable | quote }}
  token.issuer: {{ .Values.config.token.issuer | quote }}

  console.tokenProvider: {{ .Values.config.console.token.provider | quote }}
{{- end }}
