{{/*}}
不指定secret时,创建默认secret
{{*/}}
{{- if empty .Values.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passport.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "passport.labels" . | nindent 4 }}
type: Opaque
data:
  db.password: {{ .Values.config.database.password | b64enc | quote }}
  token.key: {{ .Values.config.token.key | b64enc | quote }}
  redis.password: {{ .Values.config.redis.password | b64enc | quote }}
  notify.secret: {{ .Values.config.notify.secret | b64enc | quote }}
{{- end }}