apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2.fullname" . }}-hufu
  labels:
    {{- include "oauth2.labels" . | nindent 4 }}
    app.kubernetes.io/component: hufu
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oauth2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hufu
