apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tabby.fullname" . }}-resource
  labels:
    {{- include "tabby.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.resource }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tabby.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: resource
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tabby.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: resource
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tabby.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: approot
          persistentVolumeClaim:
            claimName: {{ .Values.existingClaim }}
        - name: nginx-config
          configMap:
            name: "configmap-nginx-resource"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository.resource }}:1.25"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: approot
              mountPath: "/usr/share/nginx/html"
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/"

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
